using System.Xml.Linq;
using DocuMe.Core.Markdown;
using DocuMe.Core.State;
using Shouldly;

namespace DocuMe.Core.Tests.Markdown;

/// <summary>
/// The banner's contract has two halves. Its text and panel shape are pinned because they land on
/// every published page and a human reviews all 79 of them (gate-m2-aur-review). Its relationship
/// to <see cref="ContentHash"/> is pinned because §8 hangs approval on it: the stored hash must be
/// taken from the pre-banner body, so two publishes whose banners differ only by date must store
/// the same hash and must not invalidate anyone's approval (rule §9.2).
/// </summary>
public sealed class PageBannerTests
{
    private const string Sha = "98c6df844a1b0e0d3f2c1b5a7e9d4c6f8a0b2d4e";
    private static readonly DateOnly GeneratedOn = new(2026, 7, 25);

    private static PageBanner Full() => new()
    {
        BaselineSha = Sha,
        GeneratedOn = GeneratedOn,
        DashboardTitle = "Documentation Status",
    };

    [Fact]
    public void Render_PinsThePanelAndTheText()
    {
        Full().Render().ShouldBe(
            "<ac:structured-macro ac:name=\"info\">"
            + "<ac:parameter ac:name=\"icon\">true</ac:parameter>"
            + "<ac:rich-text-body>\n"
            + "<p>Generated by DocuMe from commit " + Sha + " on 2026-07-25. "
            + "Edit the source in the repository; changes made on this page are overwritten by "
            + "the next publish.</p>\n"
            + "<p>Review status is shown by page labels and the "
            + "<ac:link><ri:page ri:content-title=\"Documentation Status\"/>"
            + "<ac:link-body>Documentation Status</ac:link-body></ac:link> page.</p>\n"
            + "</ac:rich-text-body></ac:structured-macro>");
    }

    [Fact]
    public void Render_IsWellFormedXml()
    {
        // Independent of the pinned literal above, which was written by hand: an unbalanced tag
        // would be accepted by a string comparison against an equally unbalanced expectation, and
        // rejected by Confluence at upload time on every page of the run.
        Should.NotThrow(() => XDocument.Parse(Wrap(Full().Render())));
    }

    [Theory]
    [InlineData(null)]
    [InlineData("")]
    public void Render_WithoutBaselineSha_OmitsTheCommitClause(string? baselineSha)
    {
        // What a publish before the first generation run looks like: state.baselineSha is null
        // (§5.3 types it nullable), and "from commit " with nothing after it is worse than silence.
        var banner = Full() with { BaselineSha = baselineSha };

        banner.Render().ShouldContain("<p>Generated by DocuMe on 2026-07-25. Edit the source");
        banner.Render().ShouldNotContain("from commit");
    }

    [Fact]
    public void Render_WithoutDate_OmitsTheDateClause()
    {
        var banner = Full() with { GeneratedOn = null };

        banner.Render().ShouldContain("from commit " + Sha + ". Edit the source");
        banner.Render().ShouldNotContain("2026");
    }

    [Theory]
    [InlineData(null)]
    [InlineData("")]
    public void Render_WithoutDashboardTitle_NamesLabelsOnlyAndLinksNothing(string? title)
    {
        var banner = Full() with { DashboardTitle = title };

        banner.Render().ShouldContain("<p>Review status is shown by page labels.</p>");
        banner.Render().ShouldNotContain("ac:link");
    }

    [Fact]
    public void Render_DashboardTitle_EscapedInBothTheAttributeAndTheLinkBody()
    {
        // The title is consumer-supplied (docume.json §5.1) and & is ordinary in a page title.
        // Unescaped, it is rejected by Confluence on every page, not just the dashboard.
        var banner = Full() with { DashboardTitle = "Costs & \"billing\" <docs>" };

        var rendered = banner.Render();

        rendered.ShouldContain(
            "ri:content-title=\"Costs &amp; &quot;billing&quot; &lt;docs&gt;\"");
        rendered.ShouldContain(
            "<ac:link-body>Costs &amp; \"billing\" &lt;docs&gt;</ac:link-body>");
        Should.NotThrow(() => XDocument.Parse(Wrap(rendered)));
    }

    [Fact]
    public void Render_BaselineSha_Escaped()
    {
        // A real SHA is hex, but the value is read from a committed, hand-editable state.json,
        // so the banner does not get to assume it.
        var rendered = (Full() with { BaselineSha = "not<a&sha" }).Render();

        rendered.ShouldContain("from commit not&lt;a&amp;sha ");
        Should.NotThrow(() => XDocument.Parse(Wrap(rendered)));
    }

    [Fact]
    public void Render_IsDeterministic()
    {
        // No clock, no counter: the same publish inputs produce the same banner bytes, on every
        // page and on every machine.
        Full().Render().ShouldBe(Full().Render());
    }

    [Fact]
    public void InjectInto_PutsTheBannerAboveTheBody()
    {
        const string Body = "<h2>Overview</h2>\n<p>Hello</p>\n";

        var injected = Full().InjectInto(Body);

        injected.ShouldStartWith(Full().Render());
        injected.ShouldEndWith(Body);
    }

    [Fact]
    public void InjectInto_Null_Throws()
    {
        Should.Throw<ArgumentNullException>(() => Full().InjectInto(null!));
    }

    [Fact]
    public void Publish_StoresTheHashOfThePreBannerBody_SoADateChangeCannotMoveIt()
    {
        // The §8 invariant this slice exists for. Two publishes of an unchanged page on different
        // days: the uploaded bodies differ (Confluence gets a new version), the stored hash does
        // not, so nothing invalidates approval (rule §9.2).
        var body = ConfluenceStorageConverter.Convert("## Overview\n\nHello\n");

        var monday = Publish(body, Full());
        var tuesday = Publish(body, Full() with { GeneratedOn = GeneratedOn.AddDays(1) });

        tuesday.Upload.ShouldNotBe(monday.Upload);
        tuesday.StoredHash.ShouldBe(monday.StoredHash);
    }

    [Fact]
    public void Publish_StoredHashIsNotTheHashOfWhatWasUploaded()
    {
        // Why the ordering in Publish below is load-bearing rather than stylistic: the injected
        // body is a different preimage, and ContentHash cannot tell a banner from content
        // (ContentHashTests.OfBody_BannerPrefixedBody_HashesDifferently). Hashing the upload
        // would break approval silently, so the seam is pinned here, not commented there.
        var body = ConfluenceStorageConverter.Convert("## Overview\n\nHello\n");

        var published = Publish(body, Full());

        published.StoredHash.ShouldBe(ContentHash.OfBody(body));
        published.StoredHash.ShouldNotBe(ContentHash.OfBody(published.Upload));
    }

    [Fact]
    public void Publish_BannerDoesNotMutateTheBodyItWasInjectedInto()
    {
        var body = ConfluenceStorageConverter.Convert("## Overview\n\nHello\n");
        var before = ContentHash.OfBody(body);

        Full().InjectInto(body);

        ContentHash.OfBody(body).ShouldBe(before);
    }

    /// <summary>
    /// The publish seam of §6.2 step 5, in the order the pipeline must use it: hash the converted
    /// body, then inject the banner into what gets uploaded. The whole point of the banner living
    /// outside <see cref="ConfluenceStorageConverter"/> is that this order is expressible.
    /// </summary>
    private static (string Upload, string StoredHash) Publish(string body, PageBanner banner)
        => (banner.InjectInto(body), ContentHash.OfBody(body));

    /// <summary>
    /// Wraps a storage-format fragment in a root that declares the <c>ac</c> and <c>ri</c>
    /// prefixes, so <see cref="XDocument"/> can parse it. Confluence supplies these declarations
    /// itself; a fragment carrying them would be wrong on the wire.
    /// </summary>
    private static string Wrap(string fragment)
        => "<root xmlns:ac=\"http://atlassian.com/content\" "
            + "xmlns:ri=\"http://atlassian.com/resource/identifier\">"
            + fragment
            + "</root>";
}
