using System.Globalization;
using DocuMe.Core.Markdown;
using DocuMe.Core.State;
using DocuMe.Core.Status;

namespace DocuMe.Core.Dashboard;

/// <summary>
/// The PLAN.md §6.5 "Documentation Status" page: a <see cref="StatusReport"/> rendered as Confluence
/// storage format — coverage stats, a row per page, and the legend for the markers those rows use.
/// </summary>
/// <remarks>
/// <para>
/// <strong>One model behind the dashboard and <c>docume status</c>.</strong> §6.6 defines the terminal
/// report as "same data as dashboard", so this type renders the report §6.6 already computes rather
/// than deriving its own. Two report models would disagree eventually, and the one on the wall is the
/// one nobody re-checks.
/// </para>
/// <para>
/// <strong>Pure, like the converter.</strong> Same report in, same bytes out: no clock read
/// (<see cref="GeneratedAt"/> is a parameter), no network, no file access. That is what makes the
/// upsert able to compare the rendered body against the live one and skip a version bump when nothing
/// moved, and what makes the markup assertable without a Confluence.
/// </para>
/// <para>
/// <strong>Every consumer string is escaped.</strong> Page titles come back from Confluence (untrusted,
/// CLAUDE.md §0.2) and approver names come out of a committed file a human can hand-edit; both reach
/// the page through <see cref="ConfluenceStorageRenderer.WriteEscaped"/> rather than concatenation. A
/// stray <c>&amp;</c> is enough for Confluence to reject the whole body, and a stray <c>&lt;</c> is
/// worse than that.
/// </para>
/// <para>
/// <strong>It renders no open-feedback column</strong>, which §6.5 asks for. The comment reader is
/// <c>docume sync --comments</c> (§6.3, M4) and nothing populates the number yet;
/// <see cref="StatusReport.NotYetAvailable"/> says so on the page instead. A zero nobody counted is
/// the one thing a status page must never print.
/// </para>
/// </remarks>
public sealed record DashboardPage
{
    /// <summary>Marker for a page approved at the version Confluence currently holds.</summary>
    public const string ApprovedMarker = "✅";

    /// <summary>
    /// Marker for a page that wants a human: awaiting review, marked stale, approved at a version the
    /// wiki has since moved past, or differing from the repo. §6.5's "legend for ⚠️ markers".
    /// </summary>
    public const string AttentionMarker = "⚠️";

    /// <summary>Marker for a cell nothing has ever filled in — never a zero, never a "no".</summary>
    public const string NoneMarker = "—";

    /// <summary>How the provenance line spells an instant: minutes, UTC, no seconds and no offset.</summary>
    private const string TimestampFormat = "yyyy-MM-dd HH:mm 'UTC'";

    /// <summary>
    /// Opens the provenance line, and doubles as the split point <see cref="WithoutProvenance"/> compares
    /// up to. Written last, so nothing a consumer supplies can follow it.
    /// </summary>
    private const string ProvenanceMarker = "<p><em>Generated by DocuMe";

    /// <summary>
    /// Read by whoever lands on this page wondering why their edit vanished. States rule §9.1 where
    /// the person about to break it is looking.
    /// </summary>
    private const string OwnershipSentence =
        "This page is generated by DocuMe and rewritten in full on every run. Edits made here are lost; "
        + "the wiki source lives in the repository, and review status is set by page labels.";

    /// <summary>The report to render (§6.6).</summary>
    public required StatusReport Report { get; init; }

    /// <summary>
    /// When the run that produced <see cref="Report"/> read Confluence, for the provenance line, or
    /// <c>null</c> to omit it. A parameter rather than a clock read here for the same reason
    /// <see cref="PageBanner.GeneratedOn"/> is: a body that changes every run cannot be compared
    /// against the live one, and this page would then bump a version per cron tick forever.
    /// </summary>
    public DateTimeOffset? GeneratedAt { get; init; }

    /// <summary>Renders the whole page as a storage-format body. Deterministic.</summary>
    public string Render()
    {
        using var writer = new StringWriter();

        // The full renderer for its escaping discipline (WriteEscaped / WriteAttributeEscaped), the
        // same reason PageBanner uses it. Its object renderers are never reached: nothing here comes
        // from a parsed Markdown document.
        var renderer = new ConfluenceStorageRenderer(writer);

        WriteOwnership(renderer);
        WriteCoverage(renderer);
        WritePages(renderer);
        WriteOrphans(renderer);
        WriteFailures(renderer);
        WriteLegend(renderer);
        WriteGaps(renderer);
        WriteProvenance(renderer);

        writer.Flush();

        return writer.ToString();
    }

    private static void WriteOwnership(ConfluenceStorageRenderer renderer)
    {
        // `warning`, not `info`: the banner on a content page is provenance, but this one is a
        // don't-edit-me, and the panel colour is the part a reader takes in before the sentence.
        renderer.Write("<ac:structured-macro ac:name=\"warning\">")
            .Write("<ac:parameter ac:name=\"icon\">true</ac:parameter>")
            .Write("<ac:rich-text-body>")
            .Write('\n')
            .Write("<p>")
            .Write(OwnershipSentence)
            .Write("</p>")
            .Write('\n')
            .Write("</ac:rich-text-body></ac:structured-macro>")
            .Write('\n');
    }

    private static void WriteRow(ConfluenceStorageRenderer renderer, string tag, params string[] cells)
    {
        renderer.Write("<tr>").Write('\n');

        foreach (var cell in cells)
        {
            renderer.Write('<').Write(tag).Write('>')
                .WriteEscaped(cell)
                .Write("</").Write(tag).Write('>')
                .Write('\n');
        }

        renderer.Write("</tr>").Write('\n');
    }

    private static void WriteHeading(ConfluenceStorageRenderer renderer, string text)
    {
        // h2, not h1: §7 drops h1 from every converted page because the title owns that level, and a
        // machine-owned page that broke the convention would read as a different kind of document.
        renderer.Write("<h2>").WriteEscaped(text).Write("</h2>").Write('\n');
    }

    private static void OpenTable(ConfluenceStorageRenderer renderer)
        => renderer.Write("<table>").Write('\n').Write("<tbody>").Write('\n');

    private static void CloseTable(ConfluenceStorageRenderer renderer)
        => renderer.Write("</tbody>").Write('\n').Write("</table>").Write('\n');

    private static void WriteParagraph(ConfluenceStorageRenderer renderer, string text)
        => renderer.Write("<p>").WriteEscaped(text).Write("</p>").Write('\n');

    /// <summary>
    /// The approval half of a page's row: the marker plus the words behind it.
    /// </summary>
    /// <remarks>
    /// An approval recorded against a version the page has moved past is called out rather than shown
    /// as a plain "approved". §8 has publish invalidate approval on a content change, so the pair only
    /// diverges when something else moved the page — a browser edit, or a machine write — and a
    /// dashboard that rendered that as approved would launder it.
    /// </remarks>
    private static string ApprovalCell(StatusPage page)
    {
        if (page.Approval is not { Length: > 0 } status)
        {
            return $"{NoneMarker} no review recorded";
        }

        if (!string.Equals(status, ApprovalStatus.Approved, StringComparison.Ordinal))
        {
            return $"{AttentionMarker} {status}";
        }

        if (page.ApprovedVersion is { } approved
            && page.PublishedVersion is { } published
            && approved != published)
        {
            return $"{AttentionMarker} approved at v{approved}, page is at v{published}";
        }

        return $"{ApprovedMarker} approved";
    }

    private static string SyncCell(StatusSync sync) => sync switch
    {
        StatusSync.Unpublished => $"{AttentionMarker} not published",
        StatusSync.Drifted => $"{AttentionMarker} repo has changed",
        StatusSync.AttachmentsChanged => $"{AttentionMarker} attachments changed",
        StatusSync.Moved => $"{AttentionMarker} moved in the tree",
        _ => "in sync",
    };

    private static string Text(string? value) => value is { Length: > 0 } text ? text : NoneMarker;

    private void WriteCoverage(ConfluenceStorageRenderer renderer)
    {
        WriteHeading(renderer, "Coverage");

        var percent = Report.ApprovedPercent is { } value
            ? $"{Report.ApprovedCount} of {Report.PageCount} ({value}%)"
            : $"{Report.ApprovedCount} of {Report.PageCount}";

        OpenTable(renderer);
        WriteRow(renderer, "th", "Measure", "Pages");
        WriteRow(renderer, "td", $"{ApprovedMarker} Approved", percent);
        WriteRow(renderer, "td", $"{AttentionMarker} Needs review", $"{Report.NeedsReviewCount}");
        WriteRow(renderer, "td", $"{NoneMarker} No review recorded", $"{Report.UnrecordedApprovalCount}");
        WriteRow(renderer, "td", $"{AttentionMarker} Stale", $"{Report.StaleCount}");
        WriteRow(renderer, "td", "Published", $"{Report.PublishedCount} of {Report.PageCount}");
        CloseTable(renderer);
    }

    private void WritePages(ConfluenceStorageRenderer renderer)
    {
        WriteHeading(renderer, "Pages");

        if (Report.Pages.Count == 0)
        {
            const string empty =
                "No pages. Either the wiki root holds no markdown, or wiki.exclude filters all of it "
                + "out (docume.json, §5.1).";

            WriteParagraph(renderer, empty);
            return;
        }

        OpenTable(renderer);
        WriteRow(renderer, "th", "Page", "Review", "Approved by", "Approved on", "Stale", "Published");

        foreach (var page in Report.Pages)
        {
            renderer.Write("<tr>").Write('\n');

            WriteTitleCell(renderer, page);

            renderer.Write("<td>").WriteEscaped(ApprovalCell(page)).Write("</td>").Write('\n')
                .Write("<td>").WriteEscaped(Text(page.ApprovedBy)).Write("</td>").Write('\n')
                .Write("<td>").WriteEscaped(Text(page.ApprovedAt)).Write("</td>").Write('\n')
                .Write("<td>")
                .WriteEscaped(page.Stale ? $"{AttentionMarker} stale" : NoneMarker)
                .Write("</td>")
                .Write('\n')
                .Write("<td>").WriteEscaped(SyncCell(page.Sync)).Write("</td>").Write('\n')
                .Write("</tr>")
                .Write('\n');
        }

        CloseTable(renderer);
    }

    /// <summary>
    /// §6.5's "link" column, folded into the title cell: a linked title <em>is</em> the link, and a
    /// second column holding the same target twice costs width to say nothing.
    /// </summary>
    /// <remarks>
    /// <c>ri:page</c> rather than the <c>&lt;a href&gt;</c> <see cref="StatusPage.Url"/> would give:
    /// both target a page in this space, but Confluence rewrites its own page links when a page is
    /// renamed or moved, where a pasted URL rots silently. An unpublished page gets no link at all —
    /// an <c>ri:page</c> to a title Confluence does not hold renders as a broken link, which is a
    /// worse way to say "not published yet" than the row's own Published cell already does.
    /// </remarks>
    private static void WriteTitleCell(ConfluenceStorageRenderer renderer, StatusPage page)
    {
        renderer.Write("<td>");

        if (page.PageId is { Length: > 0 })
        {
            renderer.Write("<ac:link><ri:page ri:content-title=\"")
                .WriteAttributeEscaped(page.Title)
                .Write("\"/><ac:link-body>")
                .WriteEscaped(page.Title)
                .Write("</ac:link-body></ac:link>");
        }
        else
        {
            renderer.WriteEscaped(page.Title);
        }

        renderer.Write("</td>").Write('\n');
    }

    /// <summary>
    /// State entries whose markdown file is gone (§6.2 "Orphans"). On the dashboard because they are
    /// still live pages in Confluence: a reader may well be looking at one, and nothing else on it
    /// says the repo stopped generating it.
    /// </summary>
    private void WriteOrphans(ConfluenceStorageRenderer renderer)
    {
        if (Report.Orphans.Count == 0)
        {
            return;
        }

        WriteHeading(renderer, "Orphans");

        var lead = $"{Report.Orphans.Count} page(s) exist in Confluence with no markdown source left in "
            + "the repository. They stay published until `docume publish --prune` deletes them.";

        WriteParagraph(renderer, lead);

        OpenTable(renderer);
        WriteRow(renderer, "th", "Source path");

        foreach (var path in Report.Orphans)
        {
            WriteRow(renderer, "td", path);
        }

        CloseTable(renderer);
    }

    /// <summary>
    /// Pages the converter refuses (§7). Nothing in the wiki publishes while one exists, so the reason
    /// the rest of this page has stopped moving belongs on it.
    /// </summary>
    private void WriteFailures(ConfluenceStorageRenderer renderer)
    {
        if (Report.Failures.Count == 0)
        {
            return;
        }

        WriteHeading(renderer, "Pages that cannot publish");

        var lead = $"{Report.Failures.Count} page(s) fail conversion. No page in this wiki publishes "
            + "until every page converts, so everything above is as of the last run that succeeded.";

        WriteParagraph(renderer, lead);

        OpenTable(renderer);
        WriteRow(renderer, "th", "Source path", "Why");

        foreach (var failure in Report.Failures)
        {
            WriteRow(renderer, "td", failure.Path, failure.Message);
        }

        CloseTable(renderer);
    }

    private static void WriteLegend(ConfluenceStorageRenderer renderer)
    {
        WriteHeading(renderer, "Legend");

        OpenTable(renderer);
        WriteRow(renderer, "th", "Marker", "Meaning");
        WriteRow(
            renderer,
            "td",
            ApprovedMarker,
            "Approved by a reviewer, at the version Confluence currently holds.");
        const string attention =
            "Wants a human: awaiting review, marked stale by a source change, approved at a version the "
            + "page has moved past, or differing from the repository.";

        const string none =
            "Nothing recorded. Not a no — nobody has looked, or the label sync has not run since.";

        WriteRow(renderer, "td", AttentionMarker, attention);
        WriteRow(renderer, "td", NoneMarker, none);
        CloseTable(renderer);

        const string howTo =
            "To approve a page, add the `approved` label to it. The next `docume sync --labels` run "
            + "records that here; republishing a changed page clears it again (§8).";

        WriteParagraph(renderer, howTo);
    }

    /// <summary>
    /// What this build cannot answer, carried straight from
    /// <see cref="StatusReport.NotYetAvailable"/>. On the page rather than left as a missing column: a
    /// gap a reader has to notice is how a dashboard gets trusted for something it never measured.
    /// </summary>
    private void WriteGaps(ConfluenceStorageRenderer renderer)
    {
        if (Report.NotYetAvailable.Count == 0)
        {
            return;
        }

        WriteHeading(renderer, "Not reported yet");

        renderer.Write("<ul>").Write('\n');

        foreach (var gap in Report.NotYetAvailable)
        {
            renderer.Write("<li>").WriteEscaped(gap).Write("</li>").Write('\n');
        }

        renderer.Write("</ul>").Write('\n');
    }

    private void WriteProvenance(ConfluenceStorageRenderer renderer)
    {
        renderer.Write(ProvenanceMarker);

        if (Report.SpaceKey is { Length: > 0 } spaceKey)
        {
            renderer.Write(" from the repository state and the live labels in ").WriteEscaped(spaceKey);
        }

        renderer.Write('.');

        if (GeneratedAt is { } generatedAt)
        {
            // "last changed", not "generated": a run whose data matches the live page writes nothing
            // (see the type's remarks), so this instant is when the content above last moved — which
            // is the question a reader of a status page is actually asking.
            renderer.Write(" Rewritten only when something above it changes; last changed ")
                .Write(generatedAt.ToUniversalTime().ToString(TimestampFormat, CultureInfo.InvariantCulture))
                .Write('.');
        }

        renderer.Write("</em></p>").Write('\n');
    }

    /// <summary>
    /// Everything above the provenance line — what two renders must share for the page to count as
    /// unchanged.
    /// </summary>
    /// <remarks>
    /// <para>
    /// The same move §9.2 makes for the content hash, for the same reason. The provenance line carries
    /// an instant, so a byte comparison over the whole body would call every run a change and spend a
    /// page version per cron tick; comparing the data above it means a version is spent exactly when
    /// the data moved, and the timestamp then honestly reads as when that happened.
    /// </para>
    /// <para>
    /// <see cref="string.LastIndexOf(string, StringComparison)"/> because the marker is the last thing
    /// this type writes: nothing a consumer supplies can appear after it. A body with no marker at all
    /// is returned whole, so a page a human rewrote by hand compares unequal and is overwritten, which
    /// is what §6.5's "machine-owned" means.
    /// </para>
    /// </remarks>
    /// <param name="body">A rendered dashboard body, or one read back from Confluence.</param>
    public static string WithoutProvenance(string body)
    {
        ArgumentNullException.ThrowIfNull(body);

        var marker = body.LastIndexOf(ProvenanceMarker, StringComparison.Ordinal);

        return marker < 0 ? body : body[..marker];
    }
}
