using System.Text;
using DocuMe.Core.Config;
using DocuMe.Core.Markdown;
using DocuMe.Core.Publishing;
using DocuMe.Core.State;
using Shouldly;

namespace DocuMe.Core.Tests.Publishing;

/// <summary>
/// The publish plan end to end (PLAN.md §6.2 steps 1-5, 7): tree walk, conversion, hashing, the
/// per-page decision, the §8 banner, orphans and the write lock — with no network call and no write.
/// </summary>
/// <remarks>
/// The second run's state is built the way a real run would build it
/// (<see cref="StateUpdates.RecordPublish"/> over the first run's plan) rather than hand-written, so
/// these tests exercise the actual round trip: what a publish records must be what the next publish
/// recognizes as unchanged. A hand-written hash would pass while the real pair drifted apart.
/// </remarks>
public sealed class PublishPipelineTests : IDisposable
{
    private const string BannerPrefix = "<ac:structured-macro ac:name=\"info\">";

    private static readonly DateOnly RunDate = new(2026, 7, 25);

    private readonly string _dir = Directory.CreateTempSubdirectory("docume-publish-tests").FullName;

    /// <summary>
    /// Initializes a new instance of the <see cref="PublishPipelineTests"/> class, writing the
    /// fixture wiki once — here rather than in <see cref="Tree"/>, because a test that edits or
    /// deletes a page must see its change on the next load, and a helper that rewrote the fixture
    /// every time would quietly undo it.
    /// </summary>
    public PublishPipelineTests()
    {
        const string home = """
            # Home

            See the [Setup Guide](guides/setup.md) and the ![logo](images/logo.png).
            """;

        const string setup = """
            ---
            title: Setup Guide
            ---

            # Setup

            ```mermaid
            graph TD
              A --> B
            ```

            ![logo](../images/logo.png)
            """;

        Write("README.md", home);
        Write("guides/setup.md", setup);
        WriteBytes("images/logo.png", [1, 2, 3, 4]);
    }

    public void Dispose() => Directory.Delete(_dir, recursive: true);

    [Fact]
    public void A_first_publish_creates_every_page_and_uploads_every_attachment()
    {
        var report = Plan(new DocumeState());

        report.Pages.Select(page => page.Path).ShouldBe(["README.md", "guides/setup.md"]);
        report.Pages.ShouldAllBe(page => page.Action == PagePublishAction.Create);
        report.CreateCount.ShouldBe(2);
        report.SkipCount.ShouldBe(0);
        report.Failures.ShouldBeEmpty();
        report.CanPublish.ShouldBeTrue();

        // Every attachment the pages reference is an upload: state has never seen any of them.
        var setup = Page(report, "guides/setup.md");
        setup.Attachments.Select(attachment => attachment.Name)
            .ShouldBe(["images_logo.png", DiagramName]);
        setup.Plan.ChangedAttachments.ShouldBe(["images_logo.png", DiagramName]);
        report.UploadCount.ShouldBe(3);
    }

    [Fact]
    public void The_uploaded_body_carries_the_banner_and_the_hash_does_not()
    {
        var report = Plan(new DocumeState());
        var page = Page(report, "README.md");

        page.UploadBody.ShouldNotBeNull();
        page.UploadBody.ShouldStartWith(BannerPrefix);
        page.UploadBody.ShouldContain("Generated by DocuMe on 2026-07-25");
        page.UploadBody.ShouldContain("Documentation Status");

        // §8 / rule §9.2: the hash is taken over the converter's output, so the banner is not in it.
        ContentHash.OfBody(page.UploadBody).ShouldNotBe(page.Plan.ContentHash);
    }

    /// <summary>
    /// The invariant the whole banner seam exists for: two runs on different days upload different
    /// bodies and record the same hash, so a date change cannot revoke an approval.
    /// </summary>
    [Fact]
    public void Two_runs_on_different_days_differ_only_in_the_body_they_upload()
    {
        var today = Page(Plan(new DocumeState()), "README.md");
        var tomorrow = Page(Plan(new DocumeState(), generatedOn: RunDate.AddDays(1)), "README.md");

        tomorrow.UploadBody.ShouldNotBe(today.UploadBody);
        tomorrow.Plan.ContentHash.ShouldBe(today.Plan.ContentHash);
    }

    [Fact]
    public void The_banner_date_is_the_callers_and_omitted_when_absent()
    {
        // Straight to the pipeline: the helper below always supplies a date, and "no date at all" is
        // exactly what this test is about.
        var report = PublishPipeline.Plan(Config(), Tree(), new DocumeState(), Options());

        report.GeneratedOn.ShouldBeNull();
        report.Pages.ShouldAllBe(page => !page.UploadBody!.Contains(" on 20", StringComparison.Ordinal));

        // One date for the whole run, not one per page.
        Plan(new DocumeState()).Pages
            .ShouldAllBe(page => page.UploadBody!.Contains("on 2026-07-25", StringComparison.Ordinal));
    }

    [Fact]
    public void A_second_run_over_an_unchanged_wiki_skips_every_page()
    {
        var state = Published(Plan(new DocumeState()));

        var report = Plan(state);

        report.Pages.ShouldAllBe(page => page.Action == PagePublishAction.Skip);
        report.SkipCount.ShouldBe(2);
        report.UploadCount.ShouldBe(0);
        report.UnrenderedDiagramCount.ShouldBe(0);

        // Nothing to write means no body was even assembled.
        report.Pages.ShouldAllBe(page => page.UploadBody == null);
        report.InvalidatedApprovals.ShouldBeEmpty();
    }

    /// <summary>
    /// A hand-placed image keeps its filename when its bytes change, so the body hash cannot see it.
    /// The plan must still upload the new bytes, and must not spend a page version or touch approval.
    /// </summary>
    [Fact]
    public void Changed_asset_bytes_upload_without_a_body_write()
    {
        var state = Approve(Published(Plan(new DocumeState())), "guides/setup.md");
        File.WriteAllBytes(Path.Combine(_dir, "images", "logo.png"), [9, 9, 9]);

        var report = Plan(state);

        report.AttachmentOnlyCount.ShouldBe(2);
        report.Pages.ShouldAllBe(page => page.Action == PagePublishAction.UpdateAttachments);
        report.Pages.ShouldAllBe(page => !page.Plan.WritesBody && page.UploadBody == null);
        report.Pages.ShouldAllBe(page => page.Plan.ChangedAttachments.Contains("images_logo.png"));
        report.InvalidatedApprovals.ShouldBeEmpty();
    }

    [Fact]
    public void A_body_change_on_an_approved_page_revokes_its_approval()
    {
        var state = Approve(Published(Plan(new DocumeState())), "guides/setup.md");
        File.AppendAllText(Path.Combine(_dir, "guides", "setup.md"), "\nOne more sentence.\n");

        var report = Plan(state);

        var setup = Page(report, "guides/setup.md");
        setup.Action.ShouldBe(PagePublishAction.Update);
        setup.Plan.InvalidatesApproval.ShouldBeTrue();
        setup.UploadBody.ShouldStartWith(BannerPrefix);

        report.InvalidatedApprovals.Select(page => page.Path).ShouldBe(["guides/setup.md"]);

        // The page nobody edited is untouched — a republish must not spill onto its neighbours.
        Page(report, "README.md").Action.ShouldBe(PagePublishAction.Skip);
    }

    [Fact]
    public void Force_republishes_everything_without_revoking_approval()
    {
        var state = Approve(Published(Plan(new DocumeState())), "guides/setup.md");

        var report = Plan(state, force: true);

        report.UpdateCount.ShouldBe(2);
        report.Pages.ShouldAllBe(page => page.Plan.WritesBody);
        report.UploadCount.ShouldBe(3);

        // An unchanged hash means unchanged content, and §8 invalidates on content change only.
        report.InvalidatedApprovals.ShouldBeEmpty();
    }

    [Fact]
    public void A_state_entry_whose_file_is_gone_is_reported_as_an_orphan()
    {
        var state = Published(Plan(new DocumeState()));

        // Removing the page means removing what linked to it: a link to a page that no longer exists
        // is a broken link map, and the converter fails the whole run loud rather than publishing it.
        Write("README.md", "# Home\n\nThe ![logo](images/logo.png).");
        File.Delete(Path.Combine(_dir, "guides", "setup.md"));

        var report = Plan(state);

        report.OrphanPages.ShouldBe(["guides/setup.md"]);
        report.Pages.Select(page => page.Path).ShouldBe(["README.md"]);
        Page(report, "README.md").Action.ShouldBe(PagePublishAction.Update);

        // Reported, never planned for deletion: that needs --prune and a human (rule §9.6).
        report.CanPublish.ShouldBeTrue();
    }

    [Fact]
    public void A_page_the_converter_refuses_is_a_failure_not_a_plan()
    {
        File.WriteAllText(
            Path.Combine(_dir, "diagram.md"),
            "# Legacy Diagram\n\n```plantuml\n@startuml\nA -> B\n@enduml\n```\n");

        var report = Plan(new DocumeState());

        report.Failures.Select(failure => failure.Path).ShouldBe(["diagram.md"]);
        report.Failures[0].Message.ShouldContain("plantuml");
        report.Pages.Select(page => page.Path).ShouldBe(["README.md", "guides/setup.md"]);

        // No page publishes until every page converts: a partial wiki is a broken link map.
        report.CanPublish.ShouldBeFalse();
    }

    [Fact]
    public void An_asset_attachment_carries_its_path_and_the_hash_of_the_bytes_on_disk()
    {
        var attachment = Page(Plan(new DocumeState()), "README.md").Attachments
            .Single(candidate => candidate.Kind == AttachmentKind.Asset);

        attachment.Name.ShouldBe("images_logo.png");
        attachment.AssetPath.ShouldBe("images/logo.png");
        attachment.DiagramSource.ShouldBeNull();
        attachment.ContentHash.ShouldBe(
            ContentHash.OfBytes(File.ReadAllBytes(Path.Combine(_dir, "images", "logo.png"))));
    }

    /// <summary>
    /// A plan is offline, so it cannot hash an SVG that has not been rendered. A diagram state has
    /// never seen is an upload either way; one state already knows is unchanged, because the
    /// attachment filename is itself a hash of the diagram source.
    /// </summary>
    [Fact]
    public void A_diagram_has_no_hash_until_a_run_renders_it()
    {
        var first = Page(Plan(new DocumeState()), "guides/setup.md");
        var diagram = first.Attachments.Single(candidate => candidate.Kind == AttachmentKind.Diagram);

        diagram.Name.ShouldBe(DiagramName);
        diagram.ContentHash.ShouldBeNull();
        diagram.DiagramSource.ShouldNotBeNull().ShouldContain("graph TD");
        diagram.AssetPath.ShouldBeNull();
        first.Plan.ChangedAttachments.ShouldContain(DiagramName);

        var second = Page(Plan(Published(Plan(new DocumeState()))), "guides/setup.md");
        second.Attachments.Single(candidate => candidate.Kind == AttachmentKind.Diagram)
            .ContentHash.ShouldBe(RenderedHash(DiagramName));
        second.Plan.ChangedAttachments.ShouldBeEmpty();
    }

    [Fact]
    public void A_protected_space_refuses_the_write_but_still_plans_the_run()
    {
        var config = Config() with
        {
            Confluence = new ConfluenceConfig
            {
                BaseUrl = "https://example.atlassian.net/wiki",
                SpaceKey = "AUR",
                ProtectedSpaces = ["AUR"],
            },
        };

        var report = PublishPipeline.Plan(config, Tree(), new DocumeState(), Options());

        report.SpaceKey.ShouldBe("AUR");
        report.WriteRefusal.ShouldNotBeNull();
        report.CanWrite.ShouldBeFalse();
        report.CanPublish.ShouldBeFalse();

        // The plan is still computed and reported: refusing to write is not refusing to explain.
        report.Pages.Count.ShouldBe(2);
    }

    /// <summary>
    /// The scope's whole contract (§6.2, PublishScope): it narrows what is WRITTEN, not what is KNOWN.
    /// Both halves are asserted here because both are silent when broken — an orphan list narrowed to the
    /// scope would offer the rest of the wiki to a later <c>--prune</c>, and a link map narrowed to the
    /// scope would publish a page whose links point at nothing.
    /// </summary>
    [Fact]
    public void A_scope_narrows_what_is_written_without_narrowing_what_is_known()
    {
        var state = Published(Plan(new DocumeState()));

        // A page state remembers and the tree no longer has: an orphan a scoped run must still report.
        state = StateUpdates.RecordPublish(
            state,
            "gone.md",
            new PublishedPage(
                "page-gone", "Gone", null, "sha256:gone", 1, new Dictionary<string, string>(StringComparer.Ordinal)));

        Write("README.md", "# Home\n\nRewritten, and [the guide](guides/setup.md) is still linked.\n");
        Write("guides/setup.md", "---\ntitle: Setup Guide\n---\n\n# Setup\n\nRewritten too.\n");

        var report = Plan(state, scope: PublishScope.ForPages(["README.md"]));

        var home = Page(report, "README.md");
        home.Action.ShouldBe(PagePublishAction.Update);
        home.ExcludedByScope.ShouldBeFalse();

        var setup = Page(report, "guides/setup.md");
        setup.Action.ShouldBe(PagePublishAction.Skip);
        setup.ExcludedByScope.ShouldBeTrue();
        setup.UploadBody.ShouldBeNull();
        setup.Plan.ChangedAttachments.ShouldBeEmpty();

        report.ExcludedByScope.Select(page => page.Path).ShouldBe(["guides/setup.md"]);
        report.Scope.ShouldNotBeNull().Description.ShouldBe("--page");

        // Known, not written: the whole tree was still walked, so the deleted page is still an orphan…
        report.OrphanPages.ShouldBe(["gone.md"]);

        // …and the link map still knew the title of a page this run does not publish. "the guide" is the
        // link text; "Setup Guide" can only come from the excluded page's frontmatter.
        home.UploadBody.ShouldNotBeNull().ShouldContain("Setup Guide");
    }

    /// <summary>
    /// <c>--changed-since</c> sees files, not pages, and a changed image moves no markdown. Without this,
    /// the flag would be the one publish that cannot ship a changed picture (PublishScope).
    /// </summary>
    [Fact]
    public void A_changed_asset_pulls_in_the_pages_that_reference_it()
    {
        var state = Published(Plan(new DocumeState()));

        Write("notes.md", "# Notes\n\nA new page with no image.\n");
        WriteBytes("images/logo.png", [9, 9, 9, 9]);

        var report = Plan(
            state, scope: PublishScope.ForFilesChangedSince("abc1234", ["images/logo.png"]));

        // Both pages reference the logo — README directly, setup.md as ../images/logo.png.
        foreach (var path in (string[])["README.md", "guides/setup.md"])
        {
            var page = Page(report, path);
            page.Action.ShouldBe(PagePublishAction.UpdateAttachments);
            page.ExcludedByScope.ShouldBeFalse();
            page.Plan.ChangedAttachments.ShouldBe(["images_logo.png"]);
        }

        // The new page is a create a full run would have made, and this run says so instead of making it.
        var notes = Page(report, "notes.md");
        notes.Action.ShouldBe(PagePublishAction.Skip);
        notes.ExcludedByScope.ShouldBeTrue();

        report.UploadCount.ShouldBe(2);
        report.ExcludedByScope.Select(page => page.Path).ShouldBe(["notes.md"]);
    }

    /// <summary>
    /// §8 invalidates approval on a content change the run publishes. A page the scope held back was not
    /// published, so its approval stands — the control run proves the scope is the only reason.
    /// </summary>
    [Fact]
    public void A_scope_never_revokes_the_approval_of_a_page_it_excludes()
    {
        var state = Approve(Published(Plan(new DocumeState())), "guides/setup.md");

        Write("guides/setup.md", "---\ntitle: Setup Guide\n---\n\n# Setup\n\nRewritten.\n");

        var scoped = Plan(state, scope: PublishScope.ForPages(["README.md"]));
        scoped.InvalidatedApprovals.ShouldBeEmpty();
        Page(scoped, "guides/setup.md").Plan.InvalidatesApproval.ShouldBeFalse();

        var full = Plan(state);
        full.InvalidatedApprovals.Select(page => page.Path).ShouldBe(["guides/setup.md"]);
    }

    /// <summary>
    /// A scope does not narrow §7 either. A page the converter refuses fails the whole run even when the
    /// scope excludes it: the repo is broken whichever pages this particular run was going to write, and a
    /// scoped publish that quietly tolerates an unconvertible page is how one stays broken.
    /// </summary>
    [Fact]
    public void A_page_the_converter_refuses_still_fails_a_run_that_excludes_it()
    {
        Write("legacy.md", "# Legacy\n\n```plantuml\n@startuml\nA -> B\n@enduml\n```\n");

        var report = Plan(new DocumeState(), scope: PublishScope.ForPages(["README.md"]));

        report.Failures.Select(failure => failure.Path).ShouldBe(["legacy.md"]);
        report.CanPublish.ShouldBeFalse();
    }

    /// <summary>
    /// The honest number is what the scope cost, not how many pages it named: a page that was going to be
    /// skipped anyway lost nothing.
    /// </summary>
    [Fact]
    public void A_page_that_was_going_to_be_skipped_anyway_is_not_reported_as_excluded()
    {
        var report = Plan(Published(Plan(new DocumeState())), scope: PublishScope.ForPages(["README.md"]));

        report.SkipCount.ShouldBe(2);
        report.ExcludedByScope.ShouldBeEmpty();
    }

    [Fact]
    public void Planning_touches_no_file()
    {
        var before = Snapshot();

        _ = Plan(Published(Plan(new DocumeState())), force: true);

        Snapshot().ShouldBe(before);
    }

    [Fact]
    public void Plan_rejects_null_arguments()
    {
        var tree = Tree();

        Should.Throw<ArgumentNullException>(() => PublishPipeline.Plan(null!, tree, new DocumeState()));
        Should.Throw<ArgumentNullException>(() => PublishPipeline.Plan(Config(), null!, new DocumeState()));
        Should.Throw<ArgumentNullException>(() => PublishPipeline.Plan(Config(), tree, null!));
    }

    /// <summary>The attachment filename the fixture's mermaid fence resolves to.</summary>
    private static string DiagramName => MermaidAttachmentName.ForSource("graph TD\n  A --> B");

    private static DocumeConfig Config() => new()
    {
        Confluence = new ConfluenceConfig
        {
            BaseUrl = "https://example.atlassian.net/wiki",
            SpaceKey = "DOCUMESBX",
        },
    };

    private static PublishOptions Options(
        bool force = false,
        DateOnly? generatedOn = null,
        PublishScope? scope = null) =>
        new() { Force = force, GeneratedOn = generatedOn, Scope = scope };

    private static PlannedPage Page(PublishReport report, string path) =>
        report.Pages.Single(page => string.Equals(page.Path, path, StringComparison.Ordinal));

    /// <summary>
    /// Stands in for the SVG bytes a real run would render and hash, so a second plan sees the
    /// diagram attachment the way state would actually hold it.
    /// </summary>
    private static string RenderedHash(string attachmentName) =>
        ContentHash.OfBytes(Encoding.UTF8.GetBytes($"<svg id=\"{attachmentName}\"/>"));

    /// <summary>Marks a page approved, so a later content change has an approval to revoke (§8).</summary>
    private static DocumeState Approve(DocumeState state, string path)
    {
        var page = state.Pages[path] with
        {
            Approval = new ApprovalState
            {
                Status = ApprovalStatus.Approved,
                ApprovedBy = "mirko",
                ApprovedAt = "2026-07-24T10:00:00Z",
                ApprovedVersion = 1,
            },
        };

        var pages = new Dictionary<string, PageState>(state.Pages, StringComparer.Ordinal) { [path] = page };
        return state with { Pages = pages };
    }

    private PublishReport Plan(
        DocumeState state,
        bool force = false,
        DateOnly? generatedOn = null,
        PublishScope? scope = null) =>
        PublishPipeline.Plan(Config(), Tree(), state, Options(force, generatedOn ?? RunDate, scope));

    /// <summary>
    /// The state a real run would have written after <paramref name="report"/>, via the same
    /// <see cref="StateUpdates"/> transitions the write path uses.
    /// </summary>
    private DocumeState Published(PublishReport report)
    {
        var state = new DocumeState { BaselineSha = "abc1234" };

        foreach (var page in report.Pages)
        {
            var attachments = page.Attachments.ToDictionary(
                attachment => attachment.Name,
                attachment => attachment.ContentHash ?? RenderedHash(attachment.Name),
                StringComparer.Ordinal);

            state = StateUpdates.RecordPublish(
                state,
                page.Path,
                new PublishedPage($"page-{page.Path}", page.Title, null, page.Plan.ContentHash, 1, attachments));
        }

        return StateUpdates.RecordLastPublishedSha(state, "abc1234");
    }

    private WikiTree Tree() => WikiTree.Load(_dir);

    /// <summary>Every file under the fixture with its length and last write time, for "wrote nothing".</summary>
    private List<string> Snapshot() =>
        [.. Directory.EnumerateFiles(_dir, "*", SearchOption.AllDirectories)
            .Select(file => new FileInfo(file))
            .Select(file => $"{file.FullName}|{file.Length}|{file.LastWriteTimeUtc:O}")
            .Order(StringComparer.Ordinal)];

    private void Write(string relativePath, string content) =>
        File.WriteAllText(Materialize(relativePath), content + "\n");

    private void WriteBytes(string relativePath, byte[] content) =>
        File.WriteAllBytes(Materialize(relativePath), content);

    private string Materialize(string relativePath)
    {
        var full = Path.Combine(_dir, relativePath.Replace('/', Path.DirectorySeparatorChar));
        Directory.CreateDirectory(Path.GetDirectoryName(full)!);

        return full;
    }
}
